# Generated by Django 3.1.7 on 2021-03-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210319_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['activation_date', '-timestamp']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='expiry_date',
            new_name='activation_date',
        ),
    ]
