# Generated by Django 3.1.7 on 2021-04-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210321_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-timestamp', 'activation_date']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='void',
            field=models.BooleanField(default=False),
        ),
    ]
