# Generated by Django 3.1.7 on 2021-04-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210421_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
