# Generated by Django 3.1.7 on 2021-04-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_ticket_void_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-timestamp', 'expected_activation_date']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='activation_date',
            new_name='expected_activation_date',
        ),
    ]
