# Generated by Django 3.1.7 on 2021-04-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210421_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
