# Generated by Django 3.1.7 on 2021-04-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_ticket_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expected_activation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='void_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
