# Generated by Django 3.1.7 on 2021-04-21 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210421_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
