# Generated by Django 3.1.7 on 2021-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20210421_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='product_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
