# Generated by Django 3.1.7 on 2021-05-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210506_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-pk', 'expected_activation_date']},
        ),
    ]
