# Generated by Django 3.1.7 on 2021-05-08 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210507_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
