# Generated by Django 3.1.7 on 2021-03-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20210320_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
    ]
